=== AlexDece/mmb-gui-electron/static/mmci-cli/models/model.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "id",
    "name",
    "capabilities",
    "msr",
    "description",
    "variabledim"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "al": {
      "type": "boolean"
    },
    "variabledim": {
      "type": "number"
    },
    "msr": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 33,
          "maxItems": 33
        },
        {
          "type": "null"
        }
      ]
    },
    "capabilities": {
      "type": "object",
      "required": [
        "interest",
        "inflation",
        "outputgap",
        "output",
        "mp_shock",
        "fiscal_shock"
      ],
      "properties": {
        "interest": {
          "type": "boolean"
        },
        "inflation": {
          "type": "boolean"
        },
        "outputgap": {
          "type": "boolean"
        },
        "output": {
          "type": "boolean"
        },
        "mp_shock": {
          "type": "boolean"
        },
        "fiscal_shock": {
          "type": "boolean"
        }
      }
    },
    "description": {
      "type": "object",
      "required": [
        "ac_ref",
        "paper_title",
        "journal",
        "replicants_name",
        "pub_date",
        "keywords",
        "description",
        "category",
        "authors"
      ],
      "properties": {
        "ac_ref": {
          "type": "string"
        },
        "paper_title": {
          "type": "string"
        },
        "journal": {
          "type": [
            "string",
            "null"
          ]
        },
        "replicants_name": {
          "type": [
            "string",
            "null"
          ]
        },
        "pub_date": {
          "type": "string"
        },
        "keywords": {
          "type": "array"
        },
        "description": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "authors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== AlexDece/mmb-gui-electron/static/mmci-cli/models/NK_CW09/NK_CW09.json
{
  "$schema": "../model.schema.json",
  "id": 62,
  "name": "NK_CW09",
  "capabilities": {
    "interest": true,
    "inflation": true,
    "outputgap": true,
    "output": true,
    "mp_shock": true,
    "fiscal_shock": true,
    "rules": [
      3,
      4,
      5,
      6,
      7,
      9,
      10,
      11
    ]
  },
  "description": {
    "ac_ref": "Curdia & Woodford (2009)",
    "paper_title": "Credit frictions and optimal monetary policy",
    "journal": "BIS Working Paper No 278",
    "replicants_name": "A.HÃ¼ser and M.Kontny",
    "pub_date": "2009",
    "keywords": [],
    "description": "",
    "category": "Calibrated model",
    "authors": [
      "Curdia, Vasco",
      "Woodford, Michael"
    ]
  },
  "msr": [
    "0",
    "0",
    "0",
    "0",
    "2",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    ".25",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "1",
    "0.25"
  ],
  "variabledim": 1,
  "al": false
}

=== AlexDece/mmb-gui-electron/static/mmci-cli/models/US_VMDop/US_VMDop.json
{
  "$schema": "../model.schema.json",
  "id": 56,
  "name": "US_VMDop",
  "capabilities": {
    "interest": true,
    "inflation": true,
    "outputgap": true,
    "output": true,
    "mp_shock": true,
    "fiscal_shock": false,
    "rules": [
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11
    ]
  },
  "description": {
    "ac_ref": "Verona et al. (2013) II",
    "paper_title": "(Un)anticipated monetary policy in a dsge model with a shadow\nbanking system - Optimistic times",
    "journal": "International Journal of Central Banking 9 (3), pp. 78-124",
    "replicants_name": "Fabio Verona",
    "pub_date": "2013",
    "keywords": [],
    "description": "Calibrated for optimistic times",
    "category": "Estimated US model",
    "authors": [
      "Verona, Fabio",
      "Martins, Manuel M. F.",
      "Drumond, Ines"
    ]
  },
  "msr": [
    "0.88",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "(1-0.88)*1.82*1/1.0516",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "(1-0.88)*4*0.11*0.4796/1.0516",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "1",
    "0.25"
  ],
  "variabledim": 2,
  "al": false
}

=== AlexDece/mmb-gui-electron/static/mmci-cli/models/EA_PV16/EA_PV16.json
{
  "$schema": "../model.schema.json",
  "id": 125,
  "name": "EA_PV16",
  "capabilities": {
    "interest": true,
    "inflation": true,
    "outputgap": true,
    "output": true,
    "mp_shock": true,
    "fiscal_shock": true,
    "rules": [
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11
    ]
  },
  "description": {
    "ac_ref": "Priftis & Vogel (2016)",
    "paper_title": "The Portfolio Balance Mechanism and QE in the Euro Area",
    "journal": "Manchester School, University of Manchester, vol. 84(S1), 84-105",
    "replicants_name": "original code provided by the authors",
    "pub_date": "2016",
    "keywords": [],
    "description": "",
    "category": "Estimated euro area model",
    "authors": [
      "Priftis, Romanos",
      "Vogel, Lukas"
    ]
  },
  "msr": [
    "0.82",
    "0",
    "0",
    "0",
    "0.18*1.5",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0.18*0.5",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "1",
    "0.25"
  ],
  "variabledim": 1,
  "al": false
}
