=== AlexDece/mmb-gui-electron/static/mmci-cli/schemas/model.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "model",
  "type": "object",
  "required": [
    "id",
    "name",
    "capabilities",
    "msr",
    "description",
    "variabledim",
    "al",
    "al_info",
    "shocks",
    "vars"
  ],
  "additionalProperties": false,
  "if": {
    "properties": {
      "al": {
        "const": true
      }
    }
  },
  "then": {
    "properties": {
      "al_info": {
        "$ref": "#/properties/al_info/anyOf/0"
      }
    }
  },
  "else": {
    "properties": {
      "al_info": {
        "$ref": "#/properties/al_info/anyOf/1"
      }
    }
  },
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "al": {
      "type": "boolean"
    },
    "al_info": {
      "anyOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "forwards": {
              "$ref": "common#/definitions/arrayOfStrings"
            },
            "states_long": {
              "$ref": "common#/definitions/arrayOfStrings"
            },
            "states_short": {
              "$ref": "common#/definitions/arrayOfStrings"
            }
          }
        }, {
          "type": "null"
        }
      ]
    },
    "variabledim": {
      "enum": [
        1,
        2
      ]
    },
    "msr": {
      "anyOf": [
        {
          "$ref": "common#/definitions/arrayOfCoefficients"
        },
        {
          "type": "null"
        }
      ]
    },
    "shocks": {
      "$ref": "common#/definitions/arrayOfNamesHumanReadableNames"
    },
    "vars": {
      "$ref": "common#/definitions/arrayOfNamesHumanReadableNames"
    },
    "capabilities": {
      "type": "object",
      "required": [
        "interest",
        "inflation",
        "outputgap",
        "output",
        "mp_shock",
        "fiscal_shock"
      ],
      "properties": {
        "interest": {
          "type": "boolean"
        },
        "inflation": {
          "type": "boolean"
        },
        "outputgap": {
          "type": "boolean"
        },
        "output": {
          "type": "boolean"
        },
        "mp_shock": {
          "type": "boolean"
        },
        "fiscal_shock": {
          "type": "boolean"
        }
      }
    },
    "description": {
      "$ref": "common#/definitions/description"
    }
  }
}

=== AlexDece/mmb-gui-electron/static/mmci-cli/models/US_LWY13/US_LWY13.json
{
  "$schema": "../../schemas/model.schema.json",
  "id": 112,
  "name": "US_LWY13",
  "capabilities": {
    "interest": true,
    "inflation": true,
    "outputgap": true,
    "output": true,
    "mp_shock": true,
    "fiscal_shock": true,
    "rules": [
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11
    ]
  },
  "description": {
    "ac_ref": "Leeper et al. (2013)",
    "paper_title": "Fiscal foresight and information flows",
    "journal": "Econometrica 81 (3), 1115-1145",
    "replicants_name": "Balint Tatar",
    "pub_date": "2013",
    "keywords": [],
    "description": "",
    "category": "Estimated US model",
    "authors": [
      "Leeper, Eric M.",
      "Walker, Todd B.",
      "Yang, S.-C. Susan"
    ]
  },
  "msr": [
    "0.864376848",
    "0",
    "0",
    "0",
    "0.301234915",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0.179182587*4",
    "-0.173996187*4",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "1",
    "0.25"
  ],
  "variabledim": 1,
  "al": false,
  "vars": [
    {
      "name": "b",
      "human_readable": "b"
    },
    {
      "name": "bstar",
      "human_readable": "bstar"
    },
    {
      "name": "c",
      "human_readable": "c"
    },
    {
      "name": "cnr",
      "human_readable": "cnr"
    },
    {
      "name": "cnrstar",
      "human_readable": "cnrstar"
    },
    {
      "name": "cr",
      "human_readable": "cr"
    },
    {
      "name": "crstar",
      "human_readable": "crstar"
    },
    {
      "name": "cstar",
      "human_readable": "cstar"
    },
    {
      "name": "fispol",
      "human_readable": "fispol"
    },
    {
      "name": "g",
      "human_readable": "g"
    },
    {
      "name": "gstar",
      "human_readable": "gstar"
    },
    {
      "name": "i",
      "human_readable": "i"
    },
    {
      "name": "inflation",
      "human_readable": "inflation"
    },
    {
      "name": "inflationq",
      "human_readable": "inflationq"
    },
    {
      "name": "interest",
      "human_readable": "interest"
    },
    {
      "name": "istar",
      "human_readable": "istar"
    },
    {
      "name": "k",
      "human_readable": "k"
    },
    {
      "name": "kbar",
      "human_readable": "kbar"
    },
    {
      "name": "kbarstar",
      "human_readable": "kbarstar"
    },
    {
      "name": "kstar",
      "human_readable": "kstar"
    },
    {
      "name": "l",
      "human_readable": "l"
    },
    {
      "name": "lstar",
      "human_readable": "lstar"
    },
    {
      "name": "mc",
      "human_readable": "mc"
    },
    {
      "name": "mcstar",
      "human_readable": "mcstar"
    },
    {
      "name": "output",
      "human_readable": "output"
    },
    {
      "name": "outputgap",
      "human_readable": "outputgap"
    },
    {
      "name": "pi",
      "human_readable": "pi"
    },
    {
      "name": "q",
      "human_readable": "q"
    },
    {
      "name": "qstar",
      "human_readable": "qstar"
    },
    {
      "name": "r",
      "human_readable": "r"
    },
    {
      "name": "R",
      "human_readable": "R"
    },
    {
      "name": "rk",
      "human_readable": "rk"
    },
    {
      "name": "rkstar",
      "human_readable": "rkstar"
    },
    {
      "name": "rstar",
      "human_readable": "rstar"
    },
    {
      "name": "sb",
      "human_readable": "sb"
    },
    {
      "name": "sbstar",
      "human_readable": "sbstar"
    },
    {
      "name": "tauk",
      "human_readable": "tauk"
    },
    {
      "name": "taukstar",
      "human_readable": "taukstar"
    },
    {
      "name": "taul",
      "human_readable": "taul"
    },
    {
      "name": "taulstar",
      "human_readable": "taulstar"
    },
    {
      "name": "Tk",
      "human_readable": "Tk"
    },
    {
      "name": "Tkstar",
      "human_readable": "Tkstar"
    },
    {
      "name": "Tl",
      "human_readable": "Tl"
    },
    {
      "name": "Tlstar",
      "human_readable": "Tlstar"
    },
    {
      "name": "ua",
      "human_readable": "ua"
    },
    {
      "name": "ub",
      "human_readable": "ub"
    },
    {
      "name": "ug",
      "human_readable": "ug"
    },
    {
      "name": "ui",
      "human_readable": "ui"
    },
    {
      "name": "um",
      "human_readable": "um"
    },
    {
      "name": "up",
      "human_readable": "up"
    },
    {
      "name": "utk",
      "human_readable": "utk"
    },
    {
      "name": "utl",
      "human_readable": "utl"
    },
    {
      "name": "uw",
      "human_readable": "uw"
    },
    {
      "name": "uz",
      "human_readable": "uz"
    },
    {
      "name": "v",
      "human_readable": "v"
    },
    {
      "name": "vstar",
      "human_readable": "vstar"
    },
    {
      "name": "w",
      "human_readable": "w"
    },
    {
      "name": "wstar",
      "human_readable": "wstar"
    },
    {
      "name": "y",
      "human_readable": "y"
    },
    {
      "name": "ygap",
      "human_readable": "ygap"
    },
    {
      "name": "ystar",
      "human_readable": "ystar"
    },
    {
      "name": "z",
      "human_readable": "z"
    },
    {
      "name": "zstar",
      "human_readable": "zstar"
    }
  ],
  "shocks": [
    {
      "name": "epsilona",
      "human_readable": "epsilona"
    },
    {
      "name": "epsilonb",
      "human_readable": "epsilonb"
    },
    {
      "name": "epsiloni",
      "human_readable": "epsiloni"
    },
    {
      "name": "epsilonp",
      "human_readable": "epsilonp"
    },
    {
      "name": "epsilontk",
      "human_readable": "epsilontk"
    },
    {
      "name": "epsilontl",
      "human_readable": "epsilontl"
    },
    {
      "name": "epsilonw",
      "human_readable": "epsilonw"
    },
    {
      "name": "epsilonz",
      "human_readable": "epsilonz"
    },
    {
      "name": "fiscal_",
      "human_readable": "fiscal_"
    },
    {
      "name": "interest_",
      "human_readable": "interest_"
    }
  ],
  "al_info": null
}

=== AlexDece/mmb-gui-electron/static/mmci-cli/models/US_SW07AL/US_SW07AL.json
{
  "$schema": "../../schemas/model.schema.json",
  "id": 77,
  "name": "US_SW07AL",
  "capabilities": {
    "interest": true,
    "inflation": true,
    "outputgap": true,
    "output": true,
    "mp_shock": true,
    "fiscal_shock": true,
    "rules": [
      3,
      4,
      5,
      6,
      7,
      11
    ]
  },
  "description": {
    "ac_ref": "Slobodyan & Wouters (2012)",
    "paper_title": "Learning in an estimated medium-scale DSGE model",
    "journal": "Journal of Economic Dynamics and Control 36 (1), pp. 26-46",
    "replicants_name": "S. Slobodyan",
    "pub_date": "2012",
    "keywords": [],
    "description": "",
    "category": "Adaptive learning model",
    "authors": [
      "Slobodyan, Sergey",
      "Wouters, Rafael"
    ]
  },
  "msr": [
    "0.8103",
    "0",
    "0",
    "0",
    "(1-0.8103)*2.0443",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "((1-0.8103)*0.0882+0.2247)*4",
    "-0.2247*4",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "1",
    "0.25"
  ],
  "variabledim": 1,
  "al": true,
  "al_info": {
    "forwards": [
      "c",
      "cf",
      "inve",
      "invef",
      "lab",
      "labf",
      "pinf",
      "inflationq",
      "pk",
      "pkf",
      "rk",
      "rkf",
      "w"
    ],
    "states_long": [
      "c",
      "cf",
      "inve",
      "invef",
      "kp",
      "kpf",
      "inflationq",
      "inflationqls",
      "w",
      "a",
      "b",
      "epinfma",
      "ewma",
      "g",
      "qs",
      "spinf",
      "sw",
      "interest"
    ],
    "states_short": [
      "c",
      "cf",
      "inve",
      "invef",
      "kp",
      "kpf",
      "inflationq",
      "w",
      "a",
      "b",
      "epinfma",
      "ewma",
      "g",
      "qs",
      "spinf",
      "sw",
      "interest"
    ]
  },
  "vars": [
    {
      "name": "a",
      "human_readable": "a"
    },
    {
      "name": "b",
      "human_readable": "b"
    },
    {
      "name": "c",
      "human_readable": "c"
    },
    {
      "name": "cf",
      "human_readable": "cf"
    },
    {
      "name": "eg",
      "human_readable": "eg"
    },
    {
      "name": "epinfma",
      "human_readable": "epinfma"
    },
    {
      "name": "ewma",
      "human_readable": "ewma"
    },
    {
      "name": "fispol",
      "human_readable": "fispol"
    },
    {
      "name": "g",
      "human_readable": "g"
    },
    {
      "name": "inflation",
      "human_readable": "inflation"
    },
    {
      "name": "inflationq",
      "human_readable": "inflationq"
    },
    {
      "name": "inflationql",
      "human_readable": "inflationql"
    },
    {
      "name": "inflationql2",
      "human_readable": "inflationql2"
    },
    {
      "name": "inflationqls",
      "human_readable": "inflationqls"
    },
    {
      "name": "interest",
      "human_readable": "interest"
    },
    {
      "name": "inve",
      "human_readable": "inve"
    },
    {
      "name": "invef",
      "human_readable": "invef"
    },
    {
      "name": "k",
      "human_readable": "k"
    },
    {
      "name": "kf",
      "human_readable": "kf"
    },
    {
      "name": "kp",
      "human_readable": "kp"
    },
    {
      "name": "kpf",
      "human_readable": "kpf"
    },
    {
      "name": "lab",
      "human_readable": "lab"
    },
    {
      "name": "labf",
      "human_readable": "labf"
    },
    {
      "name": "mc",
      "human_readable": "mc"
    },
    {
      "name": "ms",
      "human_readable": "ms"
    },
    {
      "name": "output",
      "human_readable": "output"
    },
    {
      "name": "outputgap",
      "human_readable": "outputgap"
    },
    {
      "name": "pinf",
      "human_readable": "pinf"
    },
    {
      "name": "pinf4",
      "human_readable": "pinf4"
    },
    {
      "name": "pk",
      "human_readable": "pk"
    },
    {
      "name": "pkf",
      "human_readable": "pkf"
    },
    {
      "name": "qs",
      "human_readable": "qs"
    },
    {
      "name": "r",
      "human_readable": "r"
    },
    {
      "name": "rk",
      "human_readable": "rk"
    },
    {
      "name": "rkf",
      "human_readable": "rkf"
    },
    {
      "name": "rrf",
      "human_readable": "rrf"
    },
    {
      "name": "spinf",
      "human_readable": "spinf"
    },
    {
      "name": "sw",
      "human_readable": "sw"
    },
    {
      "name": "w",
      "human_readable": "w"
    },
    {
      "name": "wf",
      "human_readable": "wf"
    },
    {
      "name": "y",
      "human_readable": "y"
    },
    {
      "name": "yf",
      "human_readable": "yf"
    },
    {
      "name": "zcap",
      "human_readable": "zcap"
    },
    {
      "name": "zcapf",
      "human_readable": "zcapf"
    }
  ],
  "shocks": [
    {
      "name": "ea",
      "human_readable": "ea"
    },
    {
      "name": "eb",
      "human_readable": "eb"
    },
    {
      "name": "em",
      "human_readable": "em"
    },
    {
      "name": "epinf",
      "human_readable": "epinf"
    },
    {
      "name": "eqs",
      "human_readable": "eqs"
    },
    {
      "name": "ew",
      "human_readable": "ew"
    },
    {
      "name": "fiscal_",
      "human_readable": "fiscal_"
    },
    {
      "name": "interest_",
      "human_readable": "interest_"
    }
  ]
}

=== AlexDece/mmb-gui-electron/static/mmci-cli/models/US_FGKR15/US_FGKR15.json
{
  "$schema": "../../schemas/model.schema.json",
  "id": 93,
  "name": "US_FGKR15",
  "capabilities": {
    "interest": true,
    "inflation": true,
    "outputgap": true,
    "output": true,
    "mp_shock": true,
    "fiscal_shock": true,
    "rules": [
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11
    ]
  },
  "description": {
    "ac_ref": "Fernández-Villaverde et al. (2015) (a)",
    "paper_title": "Fiscal volatility shocks and economic activity",
    "journal": "American Economic Review 105(11), pp. 3352-3384",
    "replicants_name": "Irina Popova and Uliana Sulakshina",
    "pub_date": "2015",
    "keywords": [],
    "description": "",
    "category": "Estimated US model",
    "authors": [
      "Fernández-Villaverde, Jesús",
      "Guerrón-Quintana, Pablo",
      "Kuester, Keith",
      "Rubio-Ramírez, Juan"
    ]
  },
  "msr": [
    "0.7",
    "0",
    "0",
    "0",
    "1.35*(1-0.7) ",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0.25*(1-0.7)*4",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "1",
    "0.25"
  ],
  "variabledim": 1,
  "al": false,
  "vars": [
    {
      "name": "bdt",
      "human_readable": "bdt"
    },
    {
      "name": "bdtF",
      "human_readable": "bdtF"
    },
    {
      "name": "ct",
      "human_readable": "ct"
    },
    {
      "name": "ctF",
      "human_readable": "ctF"
    },
    {
      "name": "dt",
      "human_readable": "dt"
    },
    {
      "name": "egt",
      "human_readable": "egt"
    },
    {
      "name": "fispol",
      "human_readable": "fispol"
    },
    {
      "name": "gct",
      "human_readable": "gct"
    },
    {
      "name": "gctF",
      "human_readable": "gctF"
    },
    {
      "name": "git",
      "human_readable": "git"
    },
    {
      "name": "gitF",
      "human_readable": "gitF"
    },
    {
      "name": "gt",
      "human_readable": "gt"
    },
    {
      "name": "gtF",
      "human_readable": "gtF"
    },
    {
      "name": "gwt",
      "human_readable": "gwt"
    },
    {
      "name": "gwtF",
      "human_readable": "gwtF"
    },
    {
      "name": "gyt",
      "human_readable": "gyt"
    },
    {
      "name": "gytF",
      "human_readable": "gytF"
    },
    {
      "name": "gzt",
      "human_readable": "gzt"
    },
    {
      "name": "ht",
      "human_readable": "ht"
    },
    {
      "name": "htF",
      "human_readable": "htF"
    },
    {
      "name": "inflation",
      "human_readable": "inflation"
    },
    {
      "name": "inflationq",
      "human_readable": "inflationq"
    },
    {
      "name": "inflt",
      "human_readable": "inflt"
    },
    {
      "name": "infltF",
      "human_readable": "infltF"
    },
    {
      "name": "interest",
      "human_readable": "interest"
    },
    {
      "name": "invt",
      "human_readable": "invt"
    },
    {
      "name": "invtF",
      "human_readable": "invtF"
    },
    {
      "name": "kbt",
      "human_readable": "kbt"
    },
    {
      "name": "kbtF",
      "human_readable": "kbtF"
    },
    {
      "name": "kt",
      "human_readable": "kt"
    },
    {
      "name": "ktF",
      "human_readable": "ktF"
    },
    {
      "name": "lamt",
      "human_readable": "lamt"
    },
    {
      "name": "lamtF",
      "human_readable": "lamtF"
    },
    {
      "name": "mct",
      "human_readable": "mct"
    },
    {
      "name": "mctF",
      "human_readable": "mctF"
    },
    {
      "name": "miubt",
      "human_readable": "miubt"
    },
    {
      "name": "miubtF",
      "human_readable": "miubtF"
    },
    {
      "name": "miut",
      "human_readable": "miut"
    },
    {
      "name": "miutF",
      "human_readable": "miutF"
    },
    {
      "name": "output",
      "human_readable": "output"
    },
    {
      "name": "outputgap",
      "human_readable": "outputgap"
    },
    {
      "name": "proft",
      "human_readable": "proft"
    },
    {
      "name": "proftF",
      "human_readable": "proftF"
    },
    {
      "name": "rkt",
      "human_readable": "rkt"
    },
    {
      "name": "rktF",
      "human_readable": "rktF"
    },
    {
      "name": "Rt",
      "human_readable": "Rt"
    },
    {
      "name": "RtF",
      "human_readable": "RtF"
    },
    {
      "name": "sigct",
      "human_readable": "sigct"
    },
    {
      "name": "siggt",
      "human_readable": "siggt"
    },
    {
      "name": "sigkt",
      "human_readable": "sigkt"
    },
    {
      "name": "sigwt",
      "human_readable": "sigwt"
    },
    {
      "name": "tauct",
      "human_readable": "tauct"
    },
    {
      "name": "tauctF",
      "human_readable": "tauctF"
    },
    {
      "name": "taukt",
      "human_readable": "taukt"
    },
    {
      "name": "tauktF",
      "human_readable": "tauktF"
    },
    {
      "name": "tauwt",
      "human_readable": "tauwt"
    },
    {
      "name": "tauwtF",
      "human_readable": "tauwtF"
    },
    {
      "name": "utilt",
      "human_readable": "utilt"
    },
    {
      "name": "utiltF",
      "human_readable": "utiltF"
    },
    {
      "name": "wt",
      "human_readable": "wt"
    },
    {
      "name": "wtF",
      "human_readable": "wtF"
    },
    {
      "name": "yt",
      "human_readable": "yt"
    },
    {
      "name": "ytF",
      "human_readable": "ytF"
    }
  ],
  "shocks": [
    {
      "name": "ekt",
      "human_readable": "ekt"
    },
    {
      "name": "ewt",
      "human_readable": "ewt"
    },
    {
      "name": "ezt",
      "human_readable": "ezt"
    },
    {
      "name": "fiscal_",
      "human_readable": "fiscal_"
    },
    {
      "name": "interest_",
      "human_readable": "interest_"
    },
    {
      "name": "uct",
      "human_readable": "uct"
    },
    {
      "name": "ugt",
      "human_readable": "ugt"
    },
    {
      "name": "ukt",
      "human_readable": "ukt"
    },
    {
      "name": "uwt",
      "human_readable": "uwt"
    }
  ],
  "al_info": null
}

=== AlexDece/mmb-gui-electron/static/mmci-cli/models/NK_GM05/NK_GM05.json
{
  "$schema": "../../schemas/model.schema.json",
  "id": 8,
  "name": "NK_GM05",
  "capabilities": {
    "interest": true,
    "inflation": true,
    "outputgap": true,
    "output": true,
    "mp_shock": true,
    "fiscal_shock": false,
    "rules": [
      3,
      4,
      5,
      6,
      7,
      9,
      10,
      11
    ]
  },
  "description": {
    "ac_ref": "Gali & Monacelli (2005)",
    "paper_title": "Monetary policy and exchange rate volatility in a small open economy",
    "journal": "Review of Economic Studies 72, pp. 707-734",
    "replicants_name": "Likun Wang",
    "pub_date": "2005",
    "keywords": [],
    "description": "",
    "category": "Calibrated model",
    "authors": [
      "Gali, Jord√≠",
      "Monacelli, Tommaso"
    ]
  },
  "msr": null,
  "variabledim": 2,
  "al": false,
  "vars": [
    {
      "name": "a",
      "human_readable": "a"
    },
    {
      "name": "e",
      "human_readable": "e"
    },
    {
      "name": "inflation",
      "human_readable": "inflation"
    },
    {
      "name": "inflationq",
      "human_readable": "inflationq"
    },
    {
      "name": "interest",
      "human_readable": "interest"
    },
    {
      "name": "output",
      "human_readable": "output"
    },
    {
      "name": "outputgap",
      "human_readable": "outputgap"
    },
    {
      "name": "p",
      "human_readable": "p"
    },
    {
      "name": "ph",
      "human_readable": "ph"
    },
    {
      "name": "pi",
      "human_readable": "pi"
    },
    {
      "name": "pih",
      "human_readable": "pih"
    },
    {
      "name": "pistar",
      "human_readable": "pistar"
    },
    {
      "name": "r",
      "human_readable": "r"
    },
    {
      "name": "rnat",
      "human_readable": "rnat"
    },
    {
      "name": "s",
      "human_readable": "s"
    },
    {
      "name": "x",
      "human_readable": "x"
    },
    {
      "name": "y",
      "human_readable": "y"
    },
    {
      "name": "ynat",
      "human_readable": "ynat"
    },
    {
      "name": "ystar",
      "human_readable": "ystar"
    }
  ],
  "shocks": [
    {
      "name": "a_",
      "human_readable": "a_"
    },
    {
      "name": "interest_",
      "human_readable": "interest_"
    },
    {
      "name": "ystar_",
      "human_readable": "ystar_"
    }
  ],
  "al_info": null
}
